# Generated by Django 5.1.3 on 2025-02-02 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True)),
                ('pourcentage', models.PositiveSmallIntegerField()),
                ('detteMaximale', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('adresse', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveBigIntegerField()),
                ('remise', models.PositiveBigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('typeVente', models.CharField(choices=[('detail', 'Detail'), ('en gros', 'En gros')], max_length=15)),
                ('typePayement', models.CharField(choices=[('Espece', 'Espece'), ('Pret', 'Pret'), ('Don', 'Don')], max_length=15)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommercialSoft.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.BigIntegerField()),
                ('numeroFacture', models.CharField(max_length=20, unique=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codebare', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle', models.CharField(max_length=60, unique=True)),
                ('quantite', models.IntegerField()),
                ('prixAchat', models.PositiveBigIntegerField()),
                ('prixDetail', models.PositiveBigIntegerField()),
                ('prixEnGros', models.PositiveBigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datePeremption', models.DateField(default=django.utils.timezone.now)),
                ('seuil', models.PositiveIntegerField()),
                ('commentaire', models.CharField(max_length=60)),
                ('quantiteTotal', models.PositiveBigIntegerField()),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommercialSoft.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix', models.PositiveBigIntegerField()),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.livraison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.produit')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.societe'),
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('prix', models.PositiveBigIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.commande')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommercialSoft.produit')),
            ],
            options={
                'unique_together': {('produit', 'commande')},
            },
        ),
    ]
