# Generated by Django 5.1.6 on 2025-07-10 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True)),
                ('pourcentage', models.PositiveSmallIntegerField()),
                ('detteMaximale', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('prix', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=60)),
                ('quantite', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DetteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('adresse', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InfoBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('emplacement', models.CharField(blank=True, max_length=30, null=True)),
                ('ville', models.CharField(max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('proprietaire', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.BigIntegerField()),
                ('numeroFacture', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivraisonProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix', models.PositiveBigIntegerField()),
                ('prixDetail', models.PositiveBigIntegerField()),
                ('peremption', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PretClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dateEcheance', models.DateField(default=django.utils.timezone.now)),
                ('payer', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], default='Non', max_length=5)),
                ('commentaire', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codebare', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=60, unique=True)),
                ('quantite', models.IntegerField()),
                ('prixAchat', models.PositiveBigIntegerField()),
                ('prixDetail', models.PositiveBigIntegerField()),
                ('prixEnGros', models.PositiveBigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datePeremption', models.DateField(default=django.utils.timezone.now)),
                ('seuil', models.PositiveIntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=60, null=True)),
                ('quantiteTotal', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('prix', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VersementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VersementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VersementGerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveBigIntegerField()),
                ('remise', models.PositiveBigIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('typeVente', models.CharField(choices=[('detail', 'Detail'), ('en gros', 'En gros')], default='detail', max_length=15)),
                ('typePayement', models.CharField(choices=[('Espece', 'Espece'), ('Pret', 'Pret'), ('Don', 'Don')], default='Espece', max_length=15)),
                ('montantAchat', models.PositiveBigIntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommercialSoft.client')),
            ],
        ),
    ]
