# Generated by Django 5.2.5 on 2026-07-19 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.PositiveBigIntegerField()),
                ("remise", models.PositiveBigIntegerField(default=0)),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "typeVente",
                    models.CharField(
                        choices=[("detail", "Detail"), ("en gros", "En gros")],
                        default="detail",
                        max_length=15,
                    ),
                ),
                (
                    "typePayement",
                    models.CharField(
                        choices=[
                            ("Espece", "Espece"),
                            ("Pret", "Pret"),
                            ("Don", "Don"),
                            ("Orange Money", "Orange Money"),
                        ],
                        default="Espece",
                        max_length=20,
                    ),
                ),
                ("montantAchat", models.PositiveBigIntegerField()),
                ("client_uid", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommandeClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Traitee", "Traitee"),
                            ("Rejetee", "Rejetee"),
                        ],
                        default="En attente",
                        max_length=15,
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("motifRejet", models.TextField(blank=True, max_length=500, null=True)),
                ("dateTraitement", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommandeClientProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiteDemandee", models.PositiveIntegerField()),
                (
                    "quantiteAcceptee",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("prixUnitaire", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CommandeProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("prix", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Decaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.CharField(max_length=100)),
                ("montant", models.PositiveBigIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField()),
                ("prix", models.PositiveIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetteFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.BigIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=30)),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("montant", models.BigIntegerField()),
                (
                    "numeroFacture",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "typePayement",
                    models.CharField(
                        choices=[("Espece", "Espece"), ("Pret", "Pret")],
                        default="Espece",
                        max_length=15,
                    ),
                ),
                ("client_uid", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LivraisonProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix", models.PositiveBigIntegerField()),
                ("prixEnGros", models.PositiveBigIntegerField(blank=True, default=0)),
                ("prixDetail", models.PositiveBigIntegerField()),
                ("peremption", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PretClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.BigIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("dateEcheance", models.DateField(default=django.utils.timezone.now)),
                (
                    "payer",
                    models.CharField(
                        choices=[("Non", "Non"), ("Oui", "Oui")],
                        default="Non",
                        max_length=5,
                    ),
                ),
                ("commentaire", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codebare", models.CharField(blank=True, max_length=100, null=True)),
                ("libelle", models.CharField(max_length=60)),
                ("quantite", models.IntegerField()),
                ("prixAchat", models.DecimalField(decimal_places=0, max_digits=30)),
                ("prixEnGros", models.DecimalField(decimal_places=0, max_digits=30)),
                ("prixDetail", models.DecimalField(decimal_places=0, max_digits=30)),
                (
                    "autrePrix",
                    models.DecimalField(decimal_places=0, default=0, max_digits=30),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("datePeremption", models.DateField(default=django.utils.timezone.now)),
                ("seuil", models.PositiveIntegerField(default=0)),
                ("commentaire", models.CharField(blank=True, max_length=60, null=True)),
                ("quantiteTotal", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Retour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("prix", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Societe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="VersementClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.BigIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersementFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.BigIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersementGerant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.BigIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categorie_Decaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Categorie_Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=70)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("adresse", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("matricule", models.CharField(blank=True, max_length=20, null=True)),
                ("pourcentage", models.PositiveSmallIntegerField()),
                ("detteMaximale", models.PositiveBigIntegerField()),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
            ],
        ),
    ]
