# Generated by Django 5.1.3 on 2025-02-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='commentaire',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantiteTotal',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
