# Generated by Django 5.1.6 on 2025-07-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommercialSoft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.commande'),
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.categorie_depense'),
        ),
        migrations.AddField(
            model_name='dettefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detteFournisseur', to='CommercialSoft.fournisseur'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='dettefournisseur',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='depense',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='commande',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='client',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='categorie_depense',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.fournisseur'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='dettefournisseur',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='CommercialSoft.livraison'),
        ),
        migrations.AddField(
            model_name='livraisonproduit',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.livraison'),
        ),
        migrations.AddField(
            model_name='pretclient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets', to='CommercialSoft.client'),
        ),
        migrations.AddField(
            model_name='pretclient',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommercialSoft.commande'),
        ),
        migrations.AddField(
            model_name='pretclient',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='pretclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommercialSoft.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='livraisonproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.produit'),
        ),
        migrations.AddField(
            model_name='commandeproduit',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.produit'),
        ),
        migrations.AddField(
            model_name='retour',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='retour',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.produit'),
        ),
        migrations.AddField(
            model_name='retour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.societe'),
        ),
        migrations.AddField(
            model_name='versementclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='CommercialSoft.client'),
        ),
        migrations.AddField(
            model_name='versementclient',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='versementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versementFournisseur', to='CommercialSoft.fournisseur'),
        ),
        migrations.AddField(
            model_name='versementfournisseur',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='versementgerant',
            name='info_boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialSoft.infoboutique'),
        ),
        migrations.AddField(
            model_name='versementgerant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commandeproduit',
            unique_together={('produit', 'commande')},
        ),
    ]
