# Generated by Django 5.2.5 on 2026-07-19 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CommercialSoft", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CommercialSoft.client",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="commandeclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes_commande",
                to="CommercialSoft.client",
            ),
        ),
        migrations.AddField(
            model_name="commandeclient",
            name="commande",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demande_origine",
                to="CommercialSoft.commande",
            ),
        ),
        migrations.AddField(
            model_name="commandeclient",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="commandeclient",
            name="traitePar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_traitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commandeclientproduit",
            name="demande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="CommercialSoft.commandeclient",
            ),
        ),
        migrations.AddField(
            model_name="commandeclientproduit",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="commandeproduit",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommercialSoft.commande",
            ),
        ),
        migrations.AddField(
            model_name="commandeproduit",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="decaissement",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommercialSoft.categorie_decaissement",
            ),
        ),
        migrations.AddField(
            model_name="decaissement",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="decaissement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommercialSoft.categorie_depense",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dettefournisseur",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="dettefournisseur",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detteFournisseur",
                to="CommercialSoft.fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommercialSoft.fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="dettefournisseur",
            name="facture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livraison",
                to="CommercialSoft.livraison",
            ),
        ),
        migrations.AddField(
            model_name="livraisonproduit",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="livraisonproduit",
            name="livraison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CommercialSoft.livraison",
            ),
        ),
        migrations.AddField(
            model_name="pretclient",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prets",
                to="CommercialSoft.client",
            ),
        ),
        migrations.AddField(
            model_name="pretclient",
            name="commande",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CommercialSoft.commande",
            ),
        ),
        migrations.AddField(
            model_name="pretclient",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="pretclient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="CommercialSoft.categorie",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="livraisonproduit",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CommercialSoft.produit"
            ),
        ),
        migrations.AddField(
            model_name="commandeproduit",
            name="produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CommercialSoft.produit",
            ),
        ),
        migrations.AddField(
            model_name="commandeclientproduit",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CommercialSoft.produit"
            ),
        ),
        migrations.AddField(
            model_name="retour",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="retour",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CommercialSoft.produit"
            ),
        ),
        migrations.AddField(
            model_name="retour",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="societe",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="societe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CommercialSoft.societe",
            ),
        ),
        migrations.AddField(
            model_name="versementclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versements",
                to="CommercialSoft.client",
            ),
        ),
        migrations.AddField(
            model_name="versementclient",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="versementclient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="versementfournisseur",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="versementfournisseur",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versementFournisseur",
                to="CommercialSoft.fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="versementgerant",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.entreprise"
            ),
        ),
        migrations.AddField(
            model_name="versementgerant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="categorie",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "nom"), name="categorie_nom_unique_par_entreprise"
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(
                fields=["entreprise", "date"], name="commande_entr_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commande",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "client_uid"),
                name="commande_client_uid_unique_par_entreprise",
            ),
        ),
        migrations.AddIndex(
            model_name="commandeclient",
            index=models.Index(
                fields=["entreprise", "date"], name="commandeclient_entr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decaissement",
            index=models.Index(
                fields=["entreprise", "date"], name="decaissement_entr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depense",
            index=models.Index(
                fields=["entreprise", "date"], name="depense_entr_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fournisseur",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "nom"),
                name="fournisseur_nom_unique_par_entreprise",
            ),
        ),
        migrations.AddIndex(
            model_name="livraison",
            index=models.Index(
                fields=["entreprise", "date"], name="livraison_entr_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="livraison",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "client_uid"),
                name="livraison_client_uid_unique_par_entreprise",
            ),
        ),
        migrations.AddIndex(
            model_name="dettefournisseur",
            index=models.Index(
                fields=["entreprise", "date"], name="dettefournisseur_entr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pretclient",
            index=models.Index(
                fields=["entreprise", "date"], name="pretclient_entr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["entreprise", "datePeremption"],
                name="produit_entr_peremption_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="produit",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "codebare"),
                name="produit_codebare_unique_par_entreprise",
            ),
        ),
        migrations.AddConstraint(
            model_name="produit",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "libelle"),
                name="produit_libelle_unique_par_entreprise",
            ),
        ),
        migrations.AddIndex(
            model_name="commandeproduit",
            index=models.Index(
                fields=["entreprise", "date"], name="commandeproduit_entr_date_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commandeproduit",
            unique_together={("produit", "commande")},
        ),
        migrations.AlterUniqueTogether(
            name="commandeclientproduit",
            unique_together={("demande", "produit")},
        ),
        migrations.AddIndex(
            model_name="retour",
            index=models.Index(
                fields=["entreprise", "date"], name="retour_entr_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="societe",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "nom"), name="societe_nom_unique_par_entreprise"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "nom"), name="client_nom_unique_par_entreprise"
            ),
        ),
        migrations.AddIndex(
            model_name="versementclient",
            index=models.Index(
                fields=["entreprise", "date"], name="versementclient_entr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versementfournisseur",
            index=models.Index(
                fields=["entreprise", "date"], name="versementfourn_entr_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versementgerant",
            index=models.Index(
                fields=["entreprise", "date"], name="versementgerant_entr_date_idx"
            ),
        ),
    ]
