# Generated by Django 5.1.3 on 2025-02-06 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0002_alter_produit_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraisonproduit',
            name='peremption',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='livraisonproduit',
            name='prixDetail',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
