# Generated by Django 5.1.6 on 2025-07-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='categorie_depense',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='client',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='dettefournisseur',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='pretclient',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='retour',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='versementclient',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='versementfournisseur',
            name='info_boutique',
        ),
        migrations.RemoveField(
            model_name='versementgerant',
            name='info_boutique',
        ),
    ]
