# Generated by Django 5.2.5 on 2026-08-17 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialSoft", "0002_initial"),
        ("tenants", "0003_entreprise_date_fin_contrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="special",
            field=models.BooleanField(
                default=False,
                verbose_name="Produit special (infos client requises a la vente)",
            ),
        ),
        migrations.CreateModel(
            name="ClientSpecial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=70)),
                ("prenom", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "telephone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$",
                                "Le telephone doit contenir uniquement des chiffres.",
                            )
                        ],
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="clientSpecial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="achats",
                to="CommercialSoft.clientspecial",
            ),
        ),
    ]
