# Generated by Django 5.2.5 on 2026-08-17 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialSoft", "0003_produit_special_clientspecial_commande_clientspecial"),
        ("tenants", "0003_entreprise_date_fin_contrat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empreinte_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "date_import",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("rapport", models.JSONField(default=dict)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
                (
                    "importe_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entreprise", "empreinte_sha256"],
                        name="importjournal_empreinte_idx",
                    )
                ],
            },
        ),
    ]
