# Generated by Django 5.1.3 on 2025-02-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0003_livraisonproduit_peremption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='typePayement',
            field=models.CharField(choices=[('Espece', 'Espece'), ('Pret', 'Pret'), ('Don', 'Don')], default='Espece', max_length=15),
        ),
        migrations.AlterField(
            model_name='commande',
            name='typeVente',
            field=models.CharField(choices=[('detail', 'Detail'), ('en gros', 'En gros')], default='detail', max_length=15),
        ),
    ]
