# Generated by Django 5.1.6 on 2025-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0003_remove_categorie_info_boutique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
