# Generated by Django 5.1.3 on 2025-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0004_alter_commande_typepayement_alter_commande_typevente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='remise',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
