# Generated by Django 5.1.6 on 2025-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0005_alter_categorie_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie_depense',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='depense',
            name='intitule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='numeroFacture',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='codebare',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
