# Generated by Django 5.1.6 on 2025-03-28 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0005_alter_commande_remise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=40)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Autre', 'Autre')], max_length=10)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('type', models.CharField(choices=[('Gerant', 'Gerant'), ('Gestionnaire', 'Gestionnaire'), ('Admin', 'Admin'), ('Super_Admin', 'Super Admin')], default='Gerant', max_length=25)),
                ('cree_par', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
