# Generated by Django 5.1.6 on 2025-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0006_alter_categorie_depense_nom_alter_depense_intitule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoboutique',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='infoboutique',
            name='emplacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infoboutique',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='infoboutique',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
