# Generated by Django 5.2.5 on 2026-09-29 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialSoft", "0006_versementclient_typepayement_and_more"),
        ("tenants", "0004_entreprise_montant_contrat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnulationDetteClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.BigIntegerField()),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("motif", models.CharField(max_length=200)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annulations",
                        to="CommercialSoft.client",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entreprise", "date"], name="annuldette_entr_date_idx"
                    )
                ],
            },
        ),
    ]
