# Generated by Django 5.1.6 on 2025-03-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0006_colaborateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborateur',
        ),
    ]
