# Generated by Django 5.2.5 on 2026-09-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialSoft", "0007_annulationdetteclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="perissable",
            field=models.BooleanField(
                default=True, verbose_name="Périssable (a une date de péremption)"
            ),
        ),
    ]
