# Generated by Django 5.2.5 on 2025-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0007_alter_infoboutique_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='numeroFacture',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
