# Generated by Django 5.2.5 on 2025-08-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0008_alter_livraison_numerofacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prixAchat',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixDetail',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixEnGros',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
    ]
