# Generated by Django 5.2.5 on 2025-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0009_alter_produit_prixachat_alter_produit_prixdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='client_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
