# Generated by Django 5.1.6 on 2025-04-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0010_alter_client_email_alter_pretclient_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets', to='CommercialSoft.client'),
        ),
    ]
