# Generated by Django 5.1.6 on 2025-04-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0012_alter_pretclient_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montantAchat',
            field=models.PositiveBigIntegerField(default=50000),
            preserve_default=False,
        ),
    ]
