# Generated by Django 5.2.5 on 2025-10-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0012_versementclient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='typePayement',
            field=models.CharField(choices=[('Espece', 'Espece'), ('Pret', 'Pret')], default='Espece', max_length=15),
        ),
    ]
