# Generated by Django 5.1.6 on 2025-04-14 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0013_commande_montantachat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='CommercialSoft.livraison')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detteFournisseur', to='CommercialSoft.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='VersementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versementFournisseur', to='CommercialSoft.client')),
            ],
        ),
    ]
