# Generated by Django 5.2.5 on 2025-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0013_livraison_typepayement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraisonproduit',
            name='peremption',
            field=models.DateField(blank=True, null=True),
        ),
    ]
