# Generated by Django 5.1.6 on 2025-04-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0014_dettefournisseur_versementfournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versementFournisseur', to='CommercialSoft.fournisseur'),
        ),
    ]
