# Generated by Django 5.2.5 on 2025-11-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0014_alter_livraisonproduit_peremption'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='autrePrix',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
    ]
