# Generated by Django 5.2.5 on 2026-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0015_produit_autreprix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='numeroFacture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
