# Generated by Django 5.2.5 on 2026-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0016_alter_livraison_numerofacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='retour',
            name='commentaire',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
