# Generated by Django 5.1.6 on 2025-05-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0016_versementgerant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('emplacement', models.CharField(blank=True, max_length=30, null=True)),
                ('ville', models.CharField(max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('proprietaire', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
