# Generated by Django 5.1.6 on 2025-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0017_infoboutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='codebare',
            field=models.CharField(default=4, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
