# Generated by Django 6.0.3 on 2026-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0017_retour_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retour',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='infoboutique',
            name='quantiteNegative',
            field=models.BooleanField(default=True),
        ),
    ]
