# Generated by Django 5.2.5 on 2026-06-17 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialSoft", "0019_categorie_decaissement_decaissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="commandeproduit",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="decaissement",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="depense",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="dettefournisseur",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pretclient",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="retour",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="versementclient",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="versementfournisseur",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="versementgerant",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
