# Generated by Django 5.2.5 on 2026-06-19 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CommercialSoft",
            "0020_alter_commande_date_alter_commandeproduit_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CommandeClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Traitee", "Traitee"),
                            ("Rejetee", "Rejetee"),
                        ],
                        default="En attente",
                        max_length=15,
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dateTraitement", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_commande",
                        to="CommercialSoft.client",
                    ),
                ),
                (
                    "commande",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demande_origine",
                        to="CommercialSoft.commande",
                    ),
                ),
                (
                    "traitePar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommandeClientProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiteDemandee", models.PositiveIntegerField()),
                (
                    "quantiteAcceptee",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("prixUnitaire", models.PositiveBigIntegerField()),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="CommercialSoft.commandeclient",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CommercialSoft.produit",
                    ),
                ),
            ],
            options={
                "unique_together": {("demande", "produit")},
            },
        ),
    ]
