# Generated by Django 5.2.5 on 2026-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialSoft', '0027_clientspecial_commande_clientspecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientspecial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
