# Generated by Django 5.2.5 on 2026-08-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialSoft", "0028_alter_clientspecial_id"),
        ("CommercialSoft", "0028_clientspecial_telephone_numerique"),
    ]

    operations = []
