# Generated by Django 5.2.5 on 2026-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/entreprises/"
            ),
        ),
    ]
