# Generated by Django 5.2.5 on 2026-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_entreprise_montant_contrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="delai_alerte_peremption_mois",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Un produit est « en voie de péremption » s'il périme dans ce nombre de mois.",
                verbose_name="Délai d'alerte péremption (mois)",
            ),
        ),
    ]
