"""
Django settings for WcommercialSoft project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from decouple import config
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-39-8ml6yoy4+vrl6e$m&i-gbsa(dn4hx*q=1-cqo-g_*7yr82g'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'True'

# Définir ALLOWED_HOSTS via la variable d'environnement DJANGO_ALLOWED_HOSTS
# (liste séparée par des virgules). Par défaut '*' pour ne pas casser les
# déploiements existants tant que la variable n'est pas configurée.
ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'CommercialSoft',
    'accounts',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WcommercialSoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'CommercialSoft.context_processors.demandes_commande_en_attente',
            ],
        },
    },
]

WSGI_APPLICATION = 'WcommercialSoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configuration de la base de données via variables d'environnement.
# Par defaut : SQLite (developpement). Pour la production avec MySQL,
# definir DB_ENGINE=mysql ainsi que DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT.
"""
DB_ENGINE = config('DB_ENGINE', default='sqlite')

if DB_ENGINE == 'mysql':
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME', default='nkela_db'),
            'USER': config('DB_USER', default='root'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }   
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,  # attendre au lieu d'échouer si la base est verrouillée (polling concurrent)
            },
        }
    }
"""



DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

"""


DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,  # attendre au lieu d'échouer si la base est verrouillée (polling concurrent)
            },
        }
    }
"""
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'
USE_L10N = True

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'CommercialSoft/static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
AUTH_USER_MODEL = 'accounts.CustomUser'


# Sécurité des cookies et des en-têtes HTTP.
# SECURE_SSL_REDIRECT/HSTS sont désactivés par défaut (DJANGO_SECURE_SSL=False)
# car le comportement du proxy inverse de certains déploiements n'est pas
# garanti ; à activer explicitement via la variable d'environnement une fois
# le HTTPS confirmé en production.
SECURE_SSL = os.getenv('DJANGO_SECURE_SSL', 'False') == 'True'

SESSION_COOKIE_SECURE = SECURE_SSL
CSRF_COOKIE_SECURE = SECURE_SSL
SECURE_SSL_REDIRECT = SECURE_SSL
SECURE_HSTS_SECONDS = 31536000 if SECURE_SSL else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL
SECURE_HSTS_PRELOAD = SECURE_SSL

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True


# Configuration du pwa
PWA_APP_NAME = 'Commercial soft'
PWA_APP_SHORT_NAME = 'Commerce'
PWA_APP_DESCRIPTION = "Application de gestion commerciale Laguisoft"
PWA_APP_THEME_COLOR = '#007bff'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/icone_16x16.png',
        'sizes': '16x16'
    },
    {
        'src': '/static/images/icone_24x24.png',
        'sizes': '24x24'
    },
    {
        'src': '/static/images/icone_32x32.png',
        'sizes': '32x32'
    },
    {
        'src': '/static/images/icone_64x64.png',
        'sizes': '64x64'
    },
    {
        'src': '/static/images/icone_128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/images/icone_256x256.png',
        'sizes': '256x256'
    },
    {
        'src': '/static/images/icone_512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/icone_16x16.png',
        'sizes': '16x16'
    },
    {
        'src': '/static/images/icone_24x24.png',
        'sizes': '24x24'
    },
    {
        'src': '/static/images/icone_32x32.png',
        'sizes': '32x32'
    },
    {
        'src': '/static/images/icone_64x64.png',
        'sizes': '64x64'
    },
    {
        'src': '/static/images/icone_128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/images/icone_256x256.png',
        'sizes': '256x256'
    },
    {
        'src': '/static/images/icone_512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icone_512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'fr-FR'

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'CommercialSoft/static/js', 'serviceworker.js')
