"""
Django settings for WcommercialSoft project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-39-8ml6yoy4+vrl6e$m&i-gbsa(dn4hx*q=1-cqo-g_*7yr82g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'CommercialSoft',
    'accounts',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WcommercialSoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WcommercialSoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'WcommercialSoft',  # Remplacez par le nom de votre base
        'USER': 'mans',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'salios',  # Mettez le mot de passe MySQL
        #'HOST': 'kindy.mysql.pythonanywhere-services.com',  # Hôte MySQL
        'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

"""
# client gberedoudolar (commercialSoft)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gberedousolar$db_gberedou',  # Remplacez par le nom de votre base
        'USER': 'gberedousolar',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        'HOST': 'gberedousolar.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}

"""



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gberedoudolar$commercialSoft',  # Remplacez par le nom de votre base
        'USER': 'gberedoudolar',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Laguisoft@dev',  # Mettez le mot de passe MySQL
        'HOST': 'gberedoudolar.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}



# client Grand sidiki lofeba (quinquailerie)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'skservice$commercialSoft',  # Remplacez par le nom de votre base
        'USER': 'skservice',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Laguisoft@dev',  # Mettez le mot de passe MySQL
        'HOST': 'skservice.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'keitaetfrere$wcommercialSoft',  # Remplacez par le nom de votre base
        'USER': 'keitaetfrere',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        'HOST': 'keitaetfrere.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'commercialSoft$laguisoft',  # Remplacez par le nom de votre base
        'USER': 'commercialSoft',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        'HOST': 'commercialSoft.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'amadoubarryetfre$dbCommercialSoft',  # Remplacez par le nom de votre base
        'USER': 'amadoubarryetfre',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        'HOST': 'amadoubarryetfrere.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'amadoubarryetfre$dbCommercialSoft',  # Remplacez par le nom de votre base
        'USER': 'amadoubarryetfre',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        'HOST': 'amadoubarryetfrere.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'etsboboetfrere$dbCommercialSoft',  # Remplacez par le nom de votre base
        'USER': 'etsboboetfrere',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Laguisoft@dev',  # Mettez le mot de passe MySQL
        'HOST': 'etsboboetfrere.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djimafa$db_djimafa',  # Remplacez par le nom de votre base
        'USER': 'djimafa',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        'HOST': 'djimafa.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kindy$db_kindy',  # Remplacez par le nom de votre base
        'USER': 'kindy',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        'HOST': 'kindy.mysql.pythonanywhere-services.com',  # Hôte MySQL
        #'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fskbussinesscom_db',  # Remplacez par le nom de votre base
        'USER': 'fskbussinesscom_fskbusiness',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        #'HOST': 'kindy.mysql.pythonanywhere-services.com',  # Hôte MySQL
        'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'commercialsoftsk_db_sk2',  # Remplacez par le nom de votre base
        'USER': 'commercialsoftsk_sk2',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        #'HOST': 'kindy.mysql.pythonanywhere-services.com',  # Hôte MySQL
        'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fskbussinesscom_lofeba',  # Remplacez par le nom de votre base
        'USER': 'fskbussinesscom_lofeba',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        #'HOST': 'kindy.mysql.pythonanywhere-services.com',  # Hôte MySQL
        'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'commercialsoftsk_db_jumelle',  # Remplacez par le nom de votre base
        'USER': 'commercialsoftsk_jumelle',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        #'HOST': 'kindy.mysql.pythonanywhere-services.com',  # Hôte MySQL
        'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lststockcom_db_10avril',  # Remplacez par le nom de votre base
        'USER': 'lststockcom_10avril',         # Remplacez par votre nom d'utilisateur
        'PASSWORD': 'Lst@dev93',  # Mettez le mot de passe MySQL
        #'HOST': 'kindy.mysql.pythonanywhere-services.com',  # Hôte MySQL
        'HOST': 'localhost',  # Hôte MySQL
        'PORT': '3306',  # Port MySQL
    }
}






DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '3306',
    }
}
"""

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'
USE_L10N = True

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'CommercialSoft/static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
AUTH_USER_MODEL = 'accounts.CustomUser'



# Configuration du pwa
PWA_APP_NAME = 'Laguisoft Technologie'
PWA_APP_SHORT_NAME = 'LST'
PWA_APP_DESCRIPTION = "Application de gestion commerciale Laguisoft"
PWA_APP_THEME_COLOR = '#007bff'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/icone_16x16.png',
        'sizes': '16x16'
    },
    {
        'src': '/static/images/icone_24x24.png',
        'sizes': '24x24'
    },
    {
        'src': '/static/images/icone_32x32.png',
        'sizes': '32x32'
    },
    {
        'src': '/static/images/icone_64x64.png',
        'sizes': '64x64'
    },
    {
        'src': '/static/images/icone_128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/images/icone_256x256.png',
        'sizes': '256x256'
    },
    {
        'src': '/static/images/icone_512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/icone_16x16.png',
        'sizes': '16x16'
    },
    {
        'src': '/static/images/icone_24x24.png',
        'sizes': '24x24'
    },
    {
        'src': '/static/images/icone_32x32.png',
        'sizes': '32x32'
    },
    {
        'src': '/static/images/icone_64x64.png',
        'sizes': '64x64'
    },
    {
        'src': '/static/images/icone_128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/images/icone_256x256.png',
        'sizes': '256x256'
    },
    {
        'src': '/static/images/icone_512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icone_512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'fr-FR'

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'CommercialSoft/static/js', 'serviceworker.js')
