# Generated by Django 5.2.5 on 2026-08-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_entreprise_date_fin_contrat"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementAbonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duree_mois",
                    models.PositiveSmallIntegerField(verbose_name="Durée (mois)"),
                ),
                ("montant", models.PositiveIntegerField(verbose_name="Montant (GNF)")),
                (
                    "payer_number",
                    models.CharField(max_length=20, verbose_name="Numéro du payeur"),
                ),
                ("merchant_reference", models.CharField(max_length=64, unique=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("CREATED", "Créé"),
                            ("PENDING", "En attente"),
                            ("REDIRECTED", "Redirigé vers le portail Djomy"),
                            ("SUCCESS", "Payé"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                            ("TIMEOUT", "Expiré"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="CREATED",
                        max_length=15,
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reponse_brute", models.JSONField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.entreprise",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
    ]
